// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcXKPYQqLj93cyW1d5m0VBcMjfw1Sc0VE',
    appId: '1:565230230023:web:335685538f3277e0c0e8a2',
    messagingSenderId: '565230230023',
    projectId: 'fluttermovie-f32bd',
    authDomain: 'fluttermovie-f32bd.firebaseapp.com',
    storageBucket: 'fluttermovie-f32bd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCv2LyMWt5j6_Q16903fEolDJZcre90JTU',
    appId: '1:565230230023:android:8874137126b969fec0e8a2',
    messagingSenderId: '565230230023',
    projectId: 'fluttermovie-f32bd',
    storageBucket: 'fluttermovie-f32bd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZOuQtRq0gEUicfOobHeCNmUQq5BJxxAc',
    appId: '1:565230230023:ios:d294177920f39a27c0e8a2',
    messagingSenderId: '565230230023',
    projectId: 'fluttermovie-f32bd',
    storageBucket: 'fluttermovie-f32bd.firebasestorage.app',
    iosBundleId: 'com.example.fluttermovie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZOuQtRq0gEUicfOobHeCNmUQq5BJxxAc',
    appId: '1:565230230023:ios:d294177920f39a27c0e8a2',
    messagingSenderId: '565230230023',
    projectId: 'fluttermovie-f32bd',
    storageBucket: 'fluttermovie-f32bd.firebasestorage.app',
    iosBundleId: 'com.example.fluttermovie',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcXKPYQqLj93cyW1d5m0VBcMjfw1Sc0VE',
    appId: '1:565230230023:web:4d7f3539e9df6278c0e8a2',
    messagingSenderId: '565230230023',
    projectId: 'fluttermovie-f32bd',
    authDomain: 'fluttermovie-f32bd.firebaseapp.com',
    storageBucket: 'fluttermovie-f32bd.firebasestorage.app',
  );
}
